"""不可删除的基础 Entry 模板。

内置标识使用 builtin: 前缀，与文件预设标识区分；可选的扩展模板仍由预设目录提供。
"""

import json
import os


BUILTIN_3D = "builtin:basic_3d"
BUILTIN_2D = "builtin:basic_2d"
BUILTIN_ROOT = "builtin:root"

# 可能存有被内置模板替代副本的位置。键为相对预设根路径，值为对应内置模板。
_SUPERSEDED = (
    ("__archetypes__/基础Entry.json",   BUILTIN_3D),
    ("__archetypes__/2d_entry_basic.json", BUILTIN_2D),
    ("__entries__/基础Entry.json",      BUILTIN_3D),
    ("__bodies__/基础Body.json",        BUILTIN_3D),
)


_PRESETS = {
    BUILTIN_3D:
    {'efx_preset_kind': 'entry',
     'format_version': 2,
     'source_label': 'basic',
     'source_counts': {'extern': 0, 'entry': 0, 'action': 0},
     'in_eof': False,
     'entry': {'kind': 'standard',
               'bodyType': 526957114,
               'unkn0': 0,
               'null': 0,
               'timl': None,
               'attributes': [{'type': 'TRANSFORM3D',
                               'fields': {'typeFlag': 1,
                                          'translate': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
                                          'rotate': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
                                          'resize': [1.0, 0.0, 1.0, 0.0, 1.0, 0.0],
                                          'rotationOrder': 4,
                                          'translation_velocity': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
                                          'translation_velocity_modifier': [1.0,
                                                                            0.0,
                                                                            1.0,
                                                                            0.0,
                                                                            1.0,
                                                                            0.0],
                                          'rotation_velocity': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
                                          'rotation_velocity_modifier': [1.0, 0.0, 1.0, 0.0, 1.0, 0.0],
                                          'scale_velocity': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
                                          'scale_velocity_modifier': [1.0, 0.0, 1.0, 0.0, 1.0, 0.0],
                                          'enableVelocityBitflag': 0}},
                              {'type': 'PARENTOPTIONS',
                               'fields': {'typeFlag': 3,
                                          'relationPos': [1, 1, 1],
                                          'relationRot': [1, 1, 1],
                                          'relationScl': [1, 1, 1],
                                          'particleUseLocal': 0,
                                          'invalidParticleScale': 0,
                                          'constRelease': 0,
                                          'constReleaseJitter': 0,
                                          'jointNo': -1}},
                              {'type': 'SPAWN',
                               'fields': {'typeFlag': 2,
                                          'maxParticles': 1,
                                          'spawnNum': 1,
                                          'spawnNumJitter': 0,
                                          'intervalFrame': 0,
                                          'intervalFrameJitter': 0,
                                          'loopNum': 1,
                                          'loopNumJitter': 0,
                                          'spawnFrame': 0,
                                          'spawnFrameJitter': 0,
                                          'emitterDelayFrame': 0,
                                          'emitterDelayFrameJitter': 0,
                                          'spawnWaitFrame': 0,
                                          'spawnWaitFrameJitter': 0,
                                          'emitterRepeatCount': 1,
                                          'altBurstInterval': 0,
                                          'altBurstIntervalJitter': 0,
                                          'spawnFlags': 0}},
                              {'type': 'LIFE',
                               'fields': {'typeFlag': 12,
                                          'fadeInDuration': 5,
                                          'fadeInDurationJitter': 0,
                                          'duration': 60,
                                          'durationJitter': 0,
                                          'unknFrame': 0,
                                          'unknFrameJitter': 0,
                                          'fadeOutDuration': 20,
                                          'fadeOutDurationJitter': 20,
                                          'timeToDeath': 0,
                                          'timeToDeathJitter': 0,
                                          'indefiniteLifespan': 0}}]}},
    BUILTIN_2D:
    {'efx_preset_kind': 'entry',
     'format_version': 2,
     'source_label': '2D_Entry',
     'source_counts': {'extern': 0, 'entry': 0, 'action': 0},
     'in_eof': False,
     'entry': {'kind': 'standard',
               'bodyType': 1013701303,
               'unkn0': 0,
               'null': 0,
               'timl': None,
               'attributes': [{'type': 'TRANSFORM2D',
                               'fields': {'typeFlag': 1,
                                          'offsetX': 0.0,
                                          'offsetY': 0.0,
                                          'rotation': 0.0,
                                          'scaleX': 1.0,
                                          'scaleY': 1.0}},
                              {'type': 'PARENTOPTIONS',
                               'fields': {'typeFlag': 3,
                                          'relationPos': [1, 1, 1],
                                          'relationRot': [1, 1, 1],
                                          'relationScl': [1, 1, 1],
                                          'particleUseLocal': 1,
                                          'invalidParticleScale': 0,
                                          'constRelease': 0,
                                          'constReleaseJitter': 0,
                                          'jointNo': -1}},
                              {'type': 'SPAWN',
                               'fields': {'typeFlag': 2,
                                          'maxParticles': 1,
                                          'spawnNum': 1,
                                          'spawnNumJitter': 0,
                                          'intervalFrame': 0,
                                          'intervalFrameJitter': 0,
                                          'loopNum': 1,
                                          'loopNumJitter': 0,
                                          'spawnFrame': 0,
                                          'spawnFrameJitter': 0,
                                          'emitterDelayFrame': 0,
                                          'emitterDelayFrameJitter': 0,
                                          'spawnWaitFrame': 0,
                                          'spawnWaitFrameJitter': 0,
                                          'emitterRepeatCount': 1,
                                          'altBurstInterval': 0,
                                          'altBurstIntervalJitter': 0,
                                          'spawnFlags': 0}},
                              {'type': 'LIFE',
                               'fields': {'typeFlag': 12,
                                          'fadeInDuration': 0,
                                          'fadeInDurationJitter': 0,
                                          'duration': 60,
                                          'durationJitter': 0,
                                          'unknFrame': 0,
                                          'unknFrameJitter': 0,
                                          'fadeOutDuration': 0,
                                          'fadeOutDurationJitter': 0,
                                          'timeToDeath': 0,
                                          'timeToDeathJitter': 0,
                                          'indefiniteLifespan': 0}},
                              {'type': 'BILLBOARD2D',
                               'fields': {'typeFlag': 5,
                                          'applicationRule': 0,
                                          'color': [87, 107, 200, 100],
                                          'colorRange': [255, 255, 255, 255],
                                          'brightness': 10.0,
                                          'brightnessJitter': 0.0,
                                          'useColorRange': 0,
                                          'blendMode': 1,
                                          'correctColorNo': 0,
                                          'colorRangeCorrectColorNo': 0,
                                          'rotation': 0.0,
                                          'rotationJitter': 0.0,
                                          'scale': 1.0,
                                          'scaleJitter': 1.0,
                                          'width': 256.0,
                                          'widthJitter': 0.0,
                                          'height': 256.0,
                                          'heightJitter': 0.0,
                                          'flowSpeed': 0.0,
                                          'flowSpeedJitter': 0.0,
                                          'flowSpeedCoef': 1.0,
                                          'flowSpeedCoefJitter': 0.0,
                                          'flowStrength': 0.0,
                                          'flowStrengthJitter': 0.0,
                                          'flowStrengthCoef': 1.0,
                                          'flowStrengthCoefJitter': 0.0,
                                          'unknFixed5_0': 0,
                                          'unknEnum5_1': 0,
                                          'path': '\x00'}},
                              {'type': 'UVSEQUENCE',
                               'fields': {'typeFlag': 5,
                                          'sequenceNo': 1,
                                          'sequenceNoJitter': 0,
                                          'patternNo': 0,
                                          'patternNoJitter': 0,
                                          'playSpeed': 0.0,
                                          'playSpeedJitter': 0.0,
                                          'playSpeedCoef': 1.0,
                                          'playSpeedCoefJitter': 0.0,
                                          'loopingMode': 8,
                                          'loopingOrientation': 0,
                                          'loopingPad': 0,
                                          'path': 'vfx\\uvs\\cm\\cm_light_000\x00'}},
                              {'type': 'SHADERSETTINGS',
                               'fields': {'typeFlag': 4,
                                          'unknEnum1': 104,
                                          'spacer': -842150656,
                                          'versionRelated': 1,
                                          'depthBias': 0.0,
                                          'softParticleDistance': 0.1,
                                          'unknBitmask3_0': 0,
                                          'unknEnum3_1': 0,
                                          'blendStateType': 1,
                                          'unkn4_0': 1.0,
                                          'unkn4_1': 0.1,
                                          'unkn4_2': 0.9,
                                          'unkn4_3': 1.0,
                                          'unkn4_4': 1.0,
                                          'unkn4_5': 1.0,
                                          'unkn4_6': 1.0,
                                          'unkn4_7': 100.0,
                                          'presetId': -1,
                                          'unkn4_9': 0.0,
                                          'unkn4_10': 0.0,
                                          'unkn4_11': 0.0,
                                          'unknFixed4_12': 0.0,
                                          'unkn4_13': 0.0,
                                          'unknBitmask4_14': 0,
                                          'unkn4_15': 0,
                                          'objectInteractionFlag0': 255,
                                          'objectInteractionFlag1': 255,
                                          'objectInteractionFlag2': 255,
                                          'objectInteractionFlag3': 255,
                                          'unknBool0': 0,
                                          'unknBool1': 1,
                                          'unknBool2': 0,
                                          'unknBool3': 0,
                                          'unknEnum5_0': 0,
                                          'unknBitmask5_1': 0}}]}},
    BUILTIN_ROOT:
    {'efx_preset_kind': 'entry',
     'format_version': 2,
     'source_label': 'Root',
     'source_counts': {'extern': 0, 'entry': 0, 'action': 0},
     'in_eof': True,
     'entry': {'kind': 'root',
               'rootType': 1228515738,
               'const0': 1,
               'const1': 0,
               'entries': [{'type': 'UNITBOUNDARY',
                            'fields': {'unkn0': 1,
                                       'boundaryType': 1,
                                       'radius': 6000.0,
                                       'boundaryMin': [-800.0, -100.0, -350.0],
                                       'boundaryMax': [800.0, 600.0, 350.0],
                                       'radius2': 0.0}},
                           {'type': 'RENDERTARGET',
                            'fields': {'path_count': 12,
                                       'path0': 'vfx\\dds\\gm\\gm001\\gm001_900\\gm001_900_04_BM\x00',
                                       'path1': 'vfx\\dds\\gm\\gm001\\gm001_900\\gm001_900_04_NM\x00',
                                       'path2': '\x00',
                                       'path3': '\x00',
                                       'path4': '\x00',
                                       'path5': '\x00',
                                       'nullField': 0,
                                       'unkn0_0': 2,
                                       'unkn0_1': 0,
                                       'unkn0_2': 0,
                                       'unkn0_3': 0,
                                       'unkn0_4': 0,
                                       'unkn0_5': 0,
                                       'unkn1_0': 1.0,
                                       'unkn1_1': 0.0,
                                       'unkn1_2': 0.0,
                                       'unkn1_3': 0.0,
                                       'unkn1_4': 0.0,
                                       'unkn1_5': 4000000.0,
                                       'unkn1_6': 16.0,
                                       'unkn1_7': 1.0,
                                       'unkn1_8': 40.0}},
                           {'type': 'LAYOUTBANK',
                            'unkn': 2,
                            'blocks': [{'count': 16,
                                        'columns': [{'blockType': 0,
                                                     'values': [145.20605,
                                                                -91.05078,
                                                                -805.76855,
                                                                -252.00586,
                                                                -76.94928,
                                                                -811.772,
                                                                -211.20508,
                                                                24.864502,
                                                                -1033.1313,
                                                                -204.77588,
                                                                -52.25708,
                                                                51.20508,
                                                                -246.03223,
                                                                -10.300842,
                                                                342.68408,
                                                                -229.96094,
                                                                -53.7984,
                                                                -421.1494,
                                                                11.476563,
                                                                -55.18744,
                                                                -109.44922,
                                                                274.437,
                                                                -21.992676,
                                                                -819.7739,
                                                                168.8457,
                                                                -61.278503,
                                                                -385.7666,
                                                                206.93408,
                                                                -78.60791,
                                                                69.561035,
                                                                -150.95996,
                                                                -81.57849,
                                                                -424.08594,
                                                                233.39453,
                                                                52.116028,
                                                                -724.2871,
                                                                -118.7666,
                                                                75.174805,
                                                                651.81934,
                                                                236.59033,
                                                                3.055908,
                                                                76.66211,
                                                                -43.283203,
                                                                10.332764,
                                                                -623.7363,
                                                                122.43164,
                                                                48.397217,
                                                                801.9502]},
                                                    {'blockType': 1,
                                                     'values': [13368,
                                                                -20153,
                                                                -15572,
                                                                0,
                                                                -18590,
                                                                -20352,
                                                                -15584,
                                                                0,
                                                                -18873,
                                                                10730,
                                                                -15576,
                                                                0,
                                                                -18902,
                                                                -20914,
                                                                -15577,
                                                                0,
                                                                -18560,
                                                                -23290,
                                                                -15584,
                                                                0,
                                                                -18667,
                                                                -20830,
                                                                -15580,
                                                                0,
                                                                9671,
                                                                -20749,
                                                                -15568,
                                                                0,
                                                                14421,
                                                                -22127,
                                                                -15587,
                                                                0,
                                                                13679,
                                                                -20509,
                                                                -15576,
                                                                0,
                                                                14014,
                                                                -20196,
                                                                -15580,
                                                                0,
                                                                -19201,
                                                                -20125,
                                                                -15576,
                                                                0,
                                                                14279,
                                                                12021,
                                                                -15584,
                                                                0,
                                                                -19449,
                                                                12572,
                                                                -15572,
                                                                0,
                                                                14350,
                                                                7862,
                                                                -15584,
                                                                0,
                                                                -20973,
                                                                9675,
                                                                -15568,
                                                                0,
                                                                13397,
                                                                11996,
                                                                -15571,
                                                                0]},
                                                    {'blockType': 4,
                                                     'values': [22080,
                                                                22080,
                                                                0,
                                                                18670,
                                                                22080,
                                                                22080,
                                                                0,
                                                                18655,
                                                                22080,
                                                                22080,
                                                                0,
                                                                18727,
                                                                22080,
                                                                22080,
                                                                0,
                                                                18666,
                                                                22080,
                                                                22080,
                                                                0,
                                                                18607,
                                                                22080,
                                                                22080,
                                                                0,
                                                                18633,
                                                                22080,
                                                                22080,
                                                                0,
                                                                18568,
                                                                22080,
                                                                22080,
                                                                0,
                                                                18593,
                                                                22080,
                                                                22080,
                                                                0,
                                                                18535,
                                                                22080,
                                                                22080,
                                                                0,
                                                                18487,
                                                                22080,
                                                                22080,
                                                                0,
                                                                18529,
                                                                22080,
                                                                22080,
                                                                0,
                                                                18435,
                                                                22080,
                                                                22080,
                                                                0,
                                                                18465,
                                                                22080,
                                                                22080,
                                                                0,
                                                                18441,
                                                                22080,
                                                                22080,
                                                                0,
                                                                18308,
                                                                22080,
                                                                22080,
                                                                0,
                                                                18403]},
                                                    {'blockType': 5,
                                                     'values': [0,
                                                                0,
                                                                0,
                                                                9830,
                                                                0,
                                                                0,
                                                                0,
                                                                9830,
                                                                0,
                                                                0,
                                                                0,
                                                                9830,
                                                                0,
                                                                0,
                                                                0,
                                                                9830,
                                                                0,
                                                                0,
                                                                0,
                                                                9830,
                                                                0,
                                                                0,
                                                                0,
                                                                9830,
                                                                0,
                                                                0,
                                                                0,
                                                                9830,
                                                                0,
                                                                0,
                                                                0,
                                                                9830,
                                                                0,
                                                                0,
                                                                0,
                                                                9830,
                                                                0,
                                                                0,
                                                                0,
                                                                9830,
                                                                0,
                                                                0,
                                                                0,
                                                                9830,
                                                                0,
                                                                0,
                                                                0,
                                                                9830,
                                                                0,
                                                                0,
                                                                0,
                                                                9830,
                                                                0,
                                                                0,
                                                                0,
                                                                9830,
                                                                0,
                                                                0,
                                                                0,
                                                                9830,
                                                                0,
                                                                0,
                                                                0,
                                                                9830]}]},
                                       {'count': 17,
                                        'columns': [{'blockType': 0,
                                                     'values': [50.984375,
                                                                17.992432,
                                                                -834.60205,
                                                                101.19629,
                                                                -13.395996,
                                                                -1228.9023,
                                                                -137.21729,
                                                                35.963745,
                                                                505.45312,
                                                                -250.17041,
                                                                -58.039246,
                                                                -192.91699,
                                                                200.68457,
                                                                42.953552,
                                                                -176.80078,
                                                                -164.95361,
                                                                -67.40106,
                                                                -463.63623,
                                                                -63.276367,
                                                                23.496948,
                                                                305.05957,
                                                                -271.5879,
                                                                -62.841797,
                                                                504.1538,
                                                                121.345215,
                                                                -10.099487,
                                                                -938.7671,
                                                                -76.02881,
                                                                76.53833,
                                                                -1045.1133,
                                                                154.8169,
                                                                -62.42737,
                                                                410.4922,
                                                                -167.79541,
                                                                68.24591,
                                                                -432.60547,
                                                                179.4502,
                                                                -51.8927,
                                                                -658.1367,
                                                                -173.66553,
                                                                -75.50354,
                                                                -143.84082,
                                                                197.15869,
                                                                2.053467,
                                                                72.6001,
                                                                14.749023,
                                                                48.255615,
                                                                -309.7915,
                                                                -173.02539,
                                                                68.50415,
                                                                -191.65381]},
                                                    {'blockType': 1,
                                                     'values': [11767,
                                                                10292,
                                                                -15568,
                                                                0,
                                                                12795,
                                                                -22957,
                                                                -15568,
                                                                0,
                                                                -19431,
                                                                11340,
                                                                -15570,
                                                                0,
                                                                -18555,
                                                                -20741,
                                                                -15584,
                                                                0,
                                                                13852,
                                                                11576,
                                                                -15576,
                                                                0,
                                                                -19175,
                                                                -20438,
                                                                -15576,
                                                                0,
                                                                -20509,
                                                                10726,
                                                                -15568,
                                                                0,
                                                                -18362,
                                                                -20509,
                                                                -15587,
                                                                0,
                                                                13255,
                                                                -23247,
                                                                -15570,
                                                                0,
                                                                -20239,
                                                                12540,
                                                                -15569,
                                                                0,
                                                                13589,
                                                                -20452,
                                                                -15576,
                                                                0,
                                                                -19051,
                                                                12428,
                                                                -15576,
                                                                0,
                                                                13838,
                                                                -20736,
                                                                -15576,
                                                                0,
                                                                -18959,
                                                                -20182,
                                                                -15577,
                                                                0,
                                                                14037,
                                                                7306,
                                                                -15578,
                                                                0,
                                                                10284,
                                                                11975,
                                                                -15568,
                                                                0,
                                                                -18904,
                                                                12512,
                                                                -15578,
                                                                0]},
                                                    {'blockType': 4,
                                                     'values': [22080,
                                                                22080,
                                                                0,
                                                                18610,
                                                                22080,
                                                                22080,
                                                                0,
                                                                18602,
                                                                22080,
                                                                22080,
                                                                0,
                                                                18587,
                                                                22080,
                                                                22080,
                                                                0,
                                                                18529,
                                                                22080,
                                                                22080,
                                                                0,
                                                                18516,
                                                                22080,
                                                                22080,
                                                                0,
                                                                18510,
                                                                22080,
                                                                22080,
                                                                0,
                                                                18553,
                                                                22080,
                                                                22080,
                                                                0,
                                                                18460,
                                                                22080,
                                                                22080,
                                                                0,
                                                                18569,
                                                                22080,
                                                                22080,
                                                                0,
                                                                18506,
                                                                22080,
                                                                22080,
                                                                0,
                                                                18527,
                                                                22080,
                                                                22080,
                                                                0,
                                                                18469,
                                                                22080,
                                                                22080,
                                                                0,
                                                                18465,
                                                                22080,
                                                                22080,
                                                                0,
                                                                18443,
                                                                22080,
                                                                22080,
                                                                0,
                                                                18350,
                                                                22080,
                                                                22080,
                                                                0,
                                                                18441,
                                                                22080,
                                                                22080,
                                                                0,
                                                                18432]},
                                                    {'blockType': 5,
                                                     'values': [0,
                                                                0,
                                                                0,
                                                                8337,
                                                                0,
                                                                0,
                                                                0,
                                                                8413,
                                                                0,
                                                                0,
                                                                0,
                                                                8494,
                                                                0,
                                                                0,
                                                                0,
                                                                8582,
                                                                0,
                                                                0,
                                                                0,
                                                                8674,
                                                                0,
                                                                0,
                                                                0,
                                                                8771,
                                                                0,
                                                                0,
                                                                0,
                                                                8871,
                                                                0,
                                                                0,
                                                                0,
                                                                8984,
                                                                0,
                                                                0,
                                                                0,
                                                                9103,
                                                                0,
                                                                0,
                                                                0,
                                                                9223,
                                                                0,
                                                                0,
                                                                0,
                                                                9293,
                                                                0,
                                                                0,
                                                                0,
                                                                9366,
                                                                0,
                                                                0,
                                                                0,
                                                                9447,
                                                                0,
                                                                0,
                                                                0,
                                                                9528,
                                                                0,
                                                                0,
                                                                0,
                                                                9614,
                                                                0,
                                                                0,
                                                                0,
                                                                9706,
                                                                0,
                                                                0,
                                                                0,
                                                                9795]}]}]}]}},
}


def is_builtin(ident: str) -> bool:
    return ident in _PRESETS


def get(ident: str):
    """返回内置模板的深拷贝，防止调用方污染源模板。"""
    import copy
    preset = _PRESETS.get(ident)
    return copy.deepcopy(preset) if preset is not None else None


def _attr_count(ident: str) -> int:
    entry = _PRESETS[ident]["entry"]
    return len(entry["attributes"]) if entry["kind"] == "standard" else 0


def items():
    """返回下拉顺序的 (标识, i18n 键, 属性数)；属性数由模板实时计算，Root 不计。"""
    return [
        (BUILTIN_3D, "preset.builtin_3d", _attr_count(BUILTIN_3D)),
        (BUILTIN_2D, "preset.builtin_2d", _attr_count(BUILTIN_2D)),
        (BUILTIN_ROOT, "preset.builtin_root", _attr_count(BUILTIN_ROOT)),
    ]


def _payload_signature(preset: dict):
    """返回属性负载指纹，用于识别与内置模板相同的副本（v1 / v2 均可）。

    显示名和元数据不参与比较；无法组装的预设返回 None，视为用户修改过。
    """
    from ..efx_format.assembly import build_preset
    try:
        body = build_preset(preset)
    except Exception:
        return None
    blocks = getattr(body, "attr_blocks", None)
    if blocks is None:
        blocks = body.entries
    return [b.serialize() for b in blocks]


def purge_superseded_copies(presets_root: str):
    """移除与内置模板负载完全相同的旧副本，并保留用户修改。

    清理失败不影响插件启用。
    """
    removed = []
    for rel, ident in _SUPERSEDED:
        path = os.path.join(presets_root, *rel.split("/"))
        if not os.path.isfile(path):
            continue
        try:
            with open(path, "r", encoding="utf-8") as f:
                on_disk = json.load(f)
        except (OSError, ValueError):
            continue
        sig = _payload_signature(on_disk)
        if sig is None or sig != _payload_signature(_PRESETS[ident]):
            continue
        try:
            os.remove(path)
            removed.append(rel)
        except OSError:
            pass
    return removed
