# -*- coding: utf-8 -*-
"""保留字段的只读表。

字段标签由 schema 的统一 accessor 提供。本模块只判定字段是否在 UI 中禁止编辑；保留字段
必须继续按原始字节导出。
"""

# 保留填充字段，键为 (type_name, ori_name)。

RESERVED_FILL_FIELDS = frozenset({
    ('BLINK', 'unkn1_0'),
    ('CHECKPUREATTRIBUTE', 'unkn1'),
    ('EMITTERSHAPEMESH', 'unkn1_0'),
    ('EMITTERSHAPEMESH', 'unkn1_1'),
    ('EMITTERSHAPEMESH', 'unkn1_2'),
    ('FADEBYEMITTERANGLE', 'unkn'),
    ('FADEBYOCCLUSION', 'spacer0'),
    ('FAKEDOF', 'unkn2'),
    ('FAKEPLANE', 'unkn4'),
    ('HOMING', 'spacer'),
    ('LIGHTNING', 'spacer0'),
    ('LIGHTNING', 'spacer05_00'),
    ('LIGHTNING', 'spacer05_14'),
    ('LIGHTNING', 'unkn02'),
    ('LIGHTNING', 'unkn03'),
    ('LIGHTNING', 'unkn05_21'),
    ('LIGHTNING', 'unkn05_46'),
    ('LIGHTNING', 'unkn07_20'),
    ('LUMINANCEBLEED', 'unkn0'),
    ('MESH', 'CD1'),
    ('NOISE', 'spacer'),
    ('OTOMOSNOW', 'unkn1'),
    ('OTOMOSNOW', 'unkn4'),
    ('OTOMOSNOW', 'unkn6'),
    ('PARENTSNOW', 'unkn1'),
    ('PARENTSNOW', 'unkn3_1'),
    ('PARENTSNOW', 'unkn4_4'),
    ('PATHCHAIN', 'unkn1'),
    ('PLSNOW', 'spacer'),
    ('PLSNOW', 'unkn5'),
    ('PTTRIGGER', 'unkn1'),
    ('RAYCAST', 'spacer0'),
    ('RAYCAST', 'spacer1'),
    ('RAYCAST', 'spacer2'),
    ('RAYCAST', 'spacer3'),
    ('RIBBON', 'spacer0'),
    ('RIBBON', 'spacer1'),
    ('RIBBON', 'spacer2'),
    ('RIBBON', 'spacer3'),
    ('RIBBON', 'spacer4'),
    ('RIBBON', 'spacer5'),
    ('RIBBON', 'spacer6'),
    ('RIBBON', 'spacer7'),
    ('RIBBON', 'spacer8'),
    ('RIBBON', 'spacer9'),
    ('RIBBON', 'unkn24'),
    ('RIBBON', 'spacer28'),
    ('RIBBONBLADE', 'spacer0'),
    ('RIBBONBLADE', 'spacer1'),
    ('RIBBONBLADE', 'spacer2'),
    ('RIBBONBLADE', 'spacer3'),
    ('RIBBONBLADE', 'head.spacer4'),
    ('RIBBONBLADE', 'head.spacer5'),
    ('RIBBONBLADE', 'tailEnd.spacer4'),
    ('RIBBONBLADE', 'tailEnd.spacer5'),
    ('SCREENSPACECOLLISION', 'spacer'),
    ('SHADERSETTINGS', 'spacer'),
    ('SHOVEL', 'spacer'),
    ('SPAWNBYANGLE', 'unkn1'),
    ('SPAWNBYOCCLUSION', 'unkn1'),
    ('STRAINRIBBON', 'spacer00'),
    ('STRAINRIBBON', 'spacer01'),
    ('STRAINRIBBON', 'spacer02'),
    ('STRAINRIBBON', 'spacer03'),
    ('TONEMAPFILTER', 'unkn1'),
    ('TUBELIGHT', 'unkn3_2'),
    ('TUBELIGHT', 'unkn5_1'),
    ('TUBELIGHT', 'unknFixed0_2_cd'),
    ('UVSEQUENCE', 'loopingPad'),

    # section_length 是自描述的剩余长度标记，不是可调参数。
    ('NOISE', 'section_length'),
    ('RIBBON', 'section_length'),
    ('DUMMY', 'section_length'),
    ('BLINK', 'section_length'),
    ('FADEBYEMITTERANGLE', 'section_length'),
    ('RAYCAST', 'section_length'),
    ('HOMING', 'section_length'),
    ('SCREENSPACECOLLISION', 'section_length'),
    ('SHOVEL', 'section_length'),
    ('PATHCHAIN', 'section_length'),
    ('PTTRIGGER', 'section_length'),
    ('SPAWNBYANGLE', 'section_length'),
    ('CHECKPUREATTRIBUTE', 'section_length'),
    ('SPAWNBYOCCLUSION', 'section_length'),
    ('FADEBYOCCLUSION', 'section_length'),
    ('PARENTSNOW', 'section_length'),
    ('OTOMOSNOW', 'section_length'),
    ('FAKEPLANE', 'section_length'),
    ('REPEATAREA', 'section_length'),
    ('FAKEDOF', 'section_length'),
})


def is_reserved_fill(type_name, ori_name) -> bool:
    """该字段是否为保留填充位（UI 关闭编辑）。"""
    return (type_name, ori_name) in RESERVED_FILL_FIELDS
