# -*- coding: utf-8 -*-
"""属性字段的常用/高级显示分档。

维护约束：
- 仅影响 UI 分组，不影响解析、编辑能力或导出。
- 可见性规则中的模式字段必须保留在常用区，避免隐藏其控制入口。
- 本表由 ``tools/gen_field_tiers.py`` 生成；持久调整应修改生成脚本的白名单或规则。
"""

# TYPE_NAME -> 该类型下归入「高级」的字段 ori_name 集合
ADVANCED_FIELDS = {
    'ALPHACORRECTION': frozenset({
        'unkn0',
        'unkn3',
        'unknFlag2',
    }),
    'BILLBOARD2D': frozenset({
        'typeFlag',
        'unknEnum5_1',
        'unknFixed5_0',
    }),
    'BILLBOARD3D': frozenset({
        'colorRangeCorrectColorNo',
        'fieldInfluenceRate',
        'fieldInfluenceRateMultiplier',
        'typeFlag',
        'unknFlag9',
    }),
    'BLINK': frozenset({
        'section_length',
        'typeFlag',
        'unkn1_0',
    }),
    'CHECKPUREATTRIBUTE': frozenset({
        'section_length',
        'typeFlag',
        'unkn1',
        'unknEnum2_0',
        'unknEnum2_1',
        'unknEnum2_2',
        'unknEnum2_3',
        'unknEnum2_4',
        'unknEnum2_5',
        'unknFixed2_6',
    }),
    'COLORCORRECTFILTER': frozenset({
        'typeFlag',
        'unknEnum0_1',
        'unknFixed0_2',
        'unknFixed0_3',
    }),
    'DUMMY': frozenset({
        'section_length',
        'typeFlag',
        'unknFixed1',
    }),
    'EMITTERBOUNDARY': frozenset({
        'typeFlag',
        'unkn1_0',
        'unkn1_1',
        'unkn1_2',
        'unkn1_3',
        'unkn1_4',
        'unkn1_5',
        'unkn1_6',
        'unkn1_7',
        'unknEnum0_1',
    }),
    'EMITTERSHAPE2D': frozenset({
        'typeFlag',
        'unknFixed22_1',
    }),
    'EMITTERSHAPE3D': frozenset({
        'typeFlag',
        'unknFlag4',
    }),
    'EMITTERSHAPEMESH': frozenset({
        'typeFlag',
        'unkn1_0',
        'unkn1_1',
        'unkn1_2',
        'unknBitmask3',
        'unknEnum2_4',
        'unknEnum2_5',
        'unknEnum2_6',
        'unknEnum2_7',
        'unknFixed0_1',
        'unknFlag2_0',
        'unknFlag2_2',
    }),
    'EXTERNREFERENCE': frozenset({
        'lerp',
        'typeFlag',
        'unknFlag1_6',
    }),
    'FADEBYANGLE': frozenset({
        'minAlpha',
        'rotOrder',
        'typeFlag',
    }),
    'FADEBYDEPTH': frozenset({
        'typeFlag',
    }),
    'FADEBYEMITTERANGLE': frozenset({
        'section_length',
        'typeFlag',
        'unkn',
    }),
    'FADEBYOCCLUSION': frozenset({
        'section_length',
        'spacer0',
        'typeFlag',
    }),
    'FAKEDOF': frozenset({
        'section_length',
        'typeFlag',
        'unkn2',
        'unkn3_0',
        'unkn3_1',
        'unkn4',
        'unknBitmask5',
        'unknFixed6',
    }),
    'FAKEPLANE': frozenset({
        'section_length',
        'typeFlag',
        'unkn2',
        'unkn4',
        'unkn5_0',
        'unkn5_1',
        'unkn5_2',
        'unkn5_4',
        'unkn5_5',
        'unkn5_6',
        'unknEnum3',
        'unknEnum5_8',
        'unknFixed1_0',
        'unknFixed5_3',
        'unknFixed5_7',
        'unknFlag1_1',
        'unknFlag1_2',
        'unknFlag1_3',
    }),
    'GUIDE': frozenset({
        'accel',
        'accelJitter',
        'initialPosition',
        'initialPositionJitter',
        'int_unkn1_0',
        'int_unkn1_1',
        'unkn16',
        'unkn17',
        'unkn18',
        'unkn19',
        'unkn21',
        'unkn22',
        'unknFixed20',
    }),
    'HOMING': frozenset({
        'section_length',
        'spacer',
        'typeFlag',
        'unknownEnum1',
    }),
    'LAYOUT': frozenset({
        'typeFlag',
        'unknFixed1_0_0',
        'unknFlag1_0_3',
        'useColumn0',
        'useColumn1',
        'useColumn2',
        'useColumn4',
        'useColumn6',
        'useColumn7',
        'unknFixed0_1',
        'unknFixed1_2',
        'unknFixed1_3',
    }),
    'LIFE': frozenset({
        'timeToDeath',
        'timeToDeathJitter',
        'typeFlag',
        'unknFrame',
        'unknFrameJitter',
    }),
    'LIGHTNING': frozenset({
        'EPVColorSlot1',
        'EPVColorSlot2',
        'spacer0',
        'spacer05_00',
        'spacer05_14',
        'typeFlag',
        'unkn02',
        'unkn03',
        'unkn04',
        'unkn05_05',
        'unkn05_06',
        'unkn05_07',
        'unkn05_10',
        'unkn05_21',
        'unkn05_46',
        'unkn07_02',
        'unkn07_05',
        'unkn07_06',
        'unkn07_07',
        'unkn07_09',
        'unkn07_10',
        'unkn07_13',
        'unkn07_14',
        'unkn07_15',
        'unkn07_16',
        'unkn07_17',
        'unkn07_18',
        'unkn07_20',
        'unkn07_25',
        'unkn07_26',
        'unkn07_27',
        'unkn10_0',
        'unkn11_0',
        'unkn11_1',
        'unknAngle13_0',
        'unknBitmask05_47',
        'unknBitmask06_0',
        'unknBitmask06_1',
        'unknBitmask07_04',
        'unknBitmask07_24',
        'unknEnum05_01',
        'unknEnum05_11',
        'unknEnum05_13',
        'unknEnum05_16',
        'unknEnum07_21',
        'unknEnum07_23',
        'unknEnum08_1',
        'unknEnum10_1',
        'unknEnum12_1',
        'unknEnum13_3',
        'unknEnum14_0',
        'unknEnum16',
        'unknFixed00_1',
        'unknFixed05_20',
        'unknFixed05_22',
        'unknFixed05_23',
        'unknFixed05_24',
        'unknFixed05_45',
        'unknFixed07_03',
        'unknFixed07_08',
        'unknFixed07_19',
        'unknFixed08_0',
        'unknFixed10_3',
        'unknFixed12_0',
        'unknFixed13_1',
        'unknFixed13_2',
        'unknFixed13_4',
        'unknFixed13_5',
        'unknFixed14_2',
        'unknFixed15_0a',
        'unknFlag05_12',
        'unknFlag05_17',
        'unknFlag05_48',
        'unknFlag07_22',
        'unknFlag10_2',
        'unknFlag14_1',
    }),
    'LINKPARTSVISIBLE': frozenset({
        'typeFlag',
        'unknEnum0_2',
        'unknFixed0_1',
    }),
    'LUMINANCEBLEED': frozenset({
        'unkn0',
    }),
    'MASTERONLY': frozenset({
        'typeFlag',
    }),
    'MATERIAL': frozenset({
        'typeFlag',
    }),
    'MESH': frozenset({
        'BeginMod3',
        'CD1',
        'typeFlag',
        'unknBool0',
        'unknBool1',
        'unknBool2',
        'unknBool3',
        'unknBool4',
        'unknBool5',
        'unknEnum5',
        'unknEnum7_0',
        'unknFixed0_1',
        'unknFixed6_1',
        'unknFlag7_1',
        'unknFlag_cm2_3',
    }),
    'NOISE': frozenset({
        'section_length',
        'spacer',
        'typeFlag',
    }),
    'OTOMOSNOW': frozenset({
        'section_length',
        'typeFlag',
        'unkn1',
        'unkn4',
        'unkn6',
        'unkn7_1',
        'unkn7_3',
        'unkn7_4',
        'unkn7_7',
        'unknEnum3',
        'unknFixed2_0',
        'unknFixed2_1',
        'unknFixed5_0',
        'unknFixed5_1',
        'unknFixed5_2',
        'unknFixed5_3',
        'unknFixed7_0',
        'unknFixed7_2',
        'unknFixed7_5',
        'unknFixed7_6',
    }),
    'PARENTEMISSIVE': frozenset({
        'typeFlag',
        'unkn7_2',
        'unkn8_1',
        'unkn8_2',
        'unknEnum1',
        'unknEnum4',
        'unknFixed8_0',
        'unknFixed8_3',
        'unknFixed8_4',
    }),
    'PARENTMATERIAL': frozenset({
        'typeFlag',
        'unknFixed0_1',
        'unknFixed1',
    }),
    'PARENTOPTIONS': frozenset({
        'typeFlag',
    }),
    'PARENTSNOW': frozenset({
        'section_length',
        'typeFlag',
        'unkn1',
        'unkn3_1',
        'unkn4_0',
        'unkn4_1',
        'unkn4_10',
        'unkn4_12',
        'unkn4_2',
        'unkn4_3',
        'unkn4_4',
        'unkn4_5',
        'unkn4_7',
        'unkn4_8',
        'unkn4_9',
        'unknEnum3_0',
        'unknFixed2',
        'unknFixed4_11',
        'unknFlag4_6',
    }),
    'PATHCHAIN': frozenset({
        'section_length',
        'typeFlag',
        'unkn1',
        'unkn2',
        'unkn4_0',
        'unkn4_2',
        'unkn4_4',
        'unkn5_1',
        'unkn5_2',
        'unkn5_3',
        'unkn5_5',
        'unknBitmask5_0',
        'unknEnum3',
        'unknEnum5_7',
        'unknFixed4_1',
        'unknFixed4_3',
        'unknFixed4_5',
        'unknFixed5_4',
        'unknFixed5_6',
        'unknFlag6',
    }),
    'PLANE': frozenset({
        'colorRangeCorrectColorNo',
        'correctColorNo',
        'typeFlag',
        'unknBitmask5_0',
        'unknEnum5_1',
        'unknFlag7_1',
    }),
    'PLEMISSIVE': frozenset({
        'NULL',
        'typeFlag',
        'unknFixed5_0',
        'unknFixed5_3',
        'unknFixed5_4',
    }),
    'PLSNOW': frozenset({
        'spacer',
        'typeFlag',
        'unkn4_0',
        'unkn4_1',
        'unkn5',
        'unkn6_0',
        'unkn6_1',
        'unknFixed0_1',
    }),
    'PTBEHAVIOR': frozenset({
        'typeFlag',
    }),
    'PTCOLLISION': frozenset({
        'typeFlag',
        'unkn02',
        'unkn03',
        'unkn1_0',
        'unkn1_1',
        'unkn1_2',
        'unkn34',
        'unkn35',
        'unkn36',
        'unkn37',
        'unknEnum04',
        'unknEnum6_0',
        'unknEnum6_1',
        'unknFixed05',
        'unknFixed6_2',
    }),
    'PTLIFE': frozenset({
        'typeFlag',
        'unknEnum3',
        'unknEnum5',
        'unknFixed1',
        'unknFrame0',
        'unknFrame0Jitter',
        'unknFrame1',
        'unknFrame1Jitter',
    }),
    'PTTRIGGER': frozenset({
        'section_length',
        'typeFlag',
        'unkn1',
        'unknEnum2',
    }),
    'RAYCAST': frozenset({
        'prop2',
        'section_length',
        'spacer0',
        'spacer1',
        'spacer2',
        'spacer3',
        'typeFlag',
    }),
    'REFRACTION': frozenset({
        'typeFlag',
    }),
    'REPEATAREA': frozenset({
        'section_length',
        'typeFlag',
        'unkn3_0',
        'unkn3_1',
        'unkn3_4',
        'unkn3_5',
        'unknEnum4',
        'unknFixed3_2',
        'unknFixed3_3',
    }),
    'RGBFIRE': frozenset({
        'typeFlag',
    }),
    'RGBWATER': frozenset({
        'typeFlag',
    }),
    'RIBBON': frozenset({
        'lengthwise_offset_relative_to_camera',
        'section_length',
        'spacer0',
        'spacer4',
        'spacer9',
        'typeFlag',
        'unkn20_0',
        'unkn20_1',
        'unkn20_2',
        'unkn20_3',
        'unkn21',
        'unkn22_0',
        'unknBool16_1',
        'unknBool16_2_0',
        'unknBool16_2_1',
        'gravityLocalSpace',
        'unknBool3a',
        'unknBool3b',
        'unknBool5',
        'unknBool7',
        'enableFadeLength',
        'unknFixed16_1_lo',
        'unknFixed17',
        'unknFixed28_0',
        'unknFixed28_param3',
        'unknFlag16_0_1',
        'unknFlag22_2',
        'enableGravity',
        'gravityX',
        'gravityY',
        'gravityZ',
    }),
    'RIBBONBLADE': frozenset({
        'NULL9',
        'spacer0',
        'spacer1',
        'spacer2',
        'spacer3',
        'typeFlag',
        'unknEnum05_1',
        'unknEnum10',
        'unknFixed0_1',
        'unknFixed12_2',
        'unknFlag07_0',
        'unknFlag08',
        'unknFlag12_0',
        'unknFlag12_1',
    }),
    'SCALEANIM': frozenset({
        'typeFlag',
    }),
    'SCREENSPACECOLLISION': frozenset({
        'section_length',
        'spacer',
        'typeFlag',
        'unknEnum1',
    }),
    'SHADERSETTINGS': frozenset({
        'spacer',
        'typeFlag',
        'unkn4_0',
        'unkn4_1',
        'unkn4_10',
        'unkn4_11',
        'unkn4_13',
        'unkn4_15',
        'unkn4_2',
        'unkn4_3',
        'unkn4_4',
        'unkn4_5',
        'unkn4_6',
        'unkn4_7',
        'unkn4_9',
        'unknBitmask3_0',
        'unknBitmask4_14',
        'unknBitmask5_1',
        'unknBool0',
        'unknBool1',
        'unknBool2',
        'unknBool3',
        'unknEnum1',
        'unknEnum3_1',
        'unknEnum5_0',
        'unknFixed4_12',
        'versionRelated',
    }),
    'SHOVEL': frozenset({
        'section_length',
        'spacer',
        'typeFlag',
        'unkn09',
        'unkn10',
        'unkn11',
        'unknBitmask16',
        'unknEnum13',
        'unknEnum14',
        'unknEnum17',
        'unknFixed12',
    }),
    'SPAWN': frozenset({
        'typeFlag',
    }),
    'SPAWNBYANGLE': frozenset({
        'section_length',
        'typeFlag',
        'unkn1',
        'unkn2',
        'unknEnum3',
        'unknFixed4',
    }),
    'SPAWNBYOCCLUSION': frozenset({
        'section_length',
        'typeFlag',
        'unkn1',
        'unknFixed2',
        'unknFixed3',
    }),
    'STRAINRIBBON': frozenset({
        'angleRelated',
        'angleRelatedJitter',
        'color3_w',
        'epv_color_slot1',
        'epv_color_slot2',
        'originReleaseFlag',
        'spacer03',
        'spacer04',
        'typeFlag',
        'unkn06_17',
        'unkn06_18',
        'unkn09_2',
        'unkn09_3',
        'unkn09_4',
        'unknBool06_08_0',
        'unknBool06_08_1',
        'unknBool06_08_2',
        'unknBool06_08_3',
        'unknEnum09_0',
        'unknEnum10_00',
        'unknEnum11',
        'unknEnum12_00',
        'unknFixed00_1',
        'unknFixed00_2',
        'unknFixed03_06',
        'unknFixed03_10',
        'unknFixed04_01',
        'unknFixed09_1',
        'unknFixed12_01',
        'unknFixed12_02',
        'unknFixed12_03',
        'unknFixed13',
    }),
    'TONEMAPFILTER': frozenset({
        'typeFlag',
        'unkn1',
        'unknFixed0_1',
        'unknFixed2_2',
    }),
    'TRANSFORM2D': frozenset({
        'scaleX',
        'scaleY',
        'typeFlag',
    }),
    'TRANSFORM3D': frozenset({
        'typeFlag',
    }),
    'TUBELIGHT': frozenset({
        'typeFlag',
        'unkn1_0',
        'unkn1_10',
        'unkn2_0',
        'unkn3_2',
        'unkn5_1',
        'unkn6b_1',
        'unknBool0_2',
        'unknFixed0_1',
        'unknFixed0_2_cd',
        'unknFixed0_2a',
        'unknFixed0_2b',
        'unknFixed1_9',
        'unknFixed3_0',
        'unknFixed3_1',
        'unknFixed5_0',
        'unknFixed6a_0',
    }),
    'TURBULENCE': frozenset({
        'typeFlag',
        'unkn1_0',
        'unkn3_0',
        'unkn3_1',
        'unkn3_2',
        'unknEnum1_1',
        'unknEnum3_3',
        'unknFlag3_4',
    }),
    'UVSEQUENCE': frozenset({
        'typeFlag',
    }),
    'UVCONTROL': frozenset({
        'typeFlag',
    }),
    'VELOCITY2D': frozenset({
        'typeFlag',
    }),
    'VELOCITY3D': frozenset({
        'minMovementThreshold',
        'rotOrder',
        'typeFlag',
    }),
}


def is_advanced_field(type_name: str, ori_name: str) -> bool:
    """判断字段是否归入高级区；未知字段保守地显示为常用。"""
    names = ADVANCED_FIELDS.get(type_name)
    return bool(names) and ori_name in names


def advanced_names(type_name: str) -> frozenset:
    """某属性类型的高级字段集合；未知类型返回空集。"""
    return ADVANCED_FIELDS.get(type_name, frozenset())
