# -*- coding: utf-8 -*-
"""旧字段名到当前 schema 字段名的导出兼容表。

维护约束：
- 仅登记同一字节位置、存储大小与 dtype 均不变的纯改名。
- 别名直接指向当前名称；多次改名时保留每个旧名称的直接映射。
- 字段拆分、合并或名称复用不能由本表安全兼容，必须重新导入。
"""

FIELD_RENAME_ALIASES = {
    # LIFE
    ("LIFE", "fadeInDuration"): "appearFrame",
    ("LIFE", "fadeInDurationJitter"): "appearFrameJitter",
    ("LIFE", "duration"): "keepFrame",
    ("LIFE", "durationJitter"): "keepFrameJitter",
    ("LIFE", "fadeOutDuration"): "vanishFrame",
    ("LIFE", "fadeOutDurationJitter"): "vanishFrameJitter",

    # BLINK
    ("BLINK", "minRate"): "minAlphaRate",
    ("BLINK", "maxRate"): "maxAlphaRate",

    # SHADERSETTINGS
    ("SHADERSETTINGS", "controlBitflag"): "blendStateType",
    ("SHADERSETTINGS", "blendState"): "blendStateType",
    ("SHADERSETTINGS", "unknFlag2"): "versionRelated",

    # HOMING
    ("HOMING", "restoringForce"): "turnRate",
    ("HOMING", "speed"): "acceleration",
    ("HOMING", "speedMultiplier"): "maxSpeed",
    ("HOMING", "initialSpeed"): "acceleration",
    ("HOMING", "targetSpeed"): "maxSpeed",
    ("HOMING", "f3"): "forceFieldSpeedScale",
    ("HOMING", "vanishDistance"): "vanishRadius",
    ("HOMING", "forceFieldDistance"): "forceFieldRadius",

    # ── EMITTERSHAPE3D ───────────────────────────────────────────────────────
    ("EMITTERSHAPE3D", "unknOrientation"): "rotationCorrect",
    ("EMITTERSHAPE3D", "scaleHorizontal"): "scanAngleHorizontal",
    ("EMITTERSHAPE3D", "scaleVertical"): "scanAngleVertical",
    ("EMITTERSHAPE3D", "unknBitmaskRadiusRelated"): "rayCastDependency",

    # EXTERNREFERENCE
    ("EXTERNREFERENCE", "unknEnum1_1"): "index0",
    ("EXTERNREFERENCE", "unknEnum1_2"): "index1",
    ("EXTERNREFERENCE", "unkn1_3"): "lerp",
    ("EXTERNREFERENCE", "unkn1_4"): "transitionDuration",
    ("EXTERNREFERENCE", "unkn1_5"): "triggerDelay",

    # RAYCAST
    ("RAYCAST", "prop3"): "startOffset",
    ("RAYCAST", "spacer"): "rayCastAttr",
    ("RAYCAST", "unknownEnum1"): "rayCastID",
    ("RAYCAST", "unknownBitmask2"): "rayCastFlags",
    ("RAYCAST", "distanceMod0"): "maxDistance",
    ("RAYCAST", "distanceMod0Jitter"): "maxDistanceJitter",
    ("RAYCAST", "prop1"): "startDistance",
    ("RAYCAST", "prop1Jitter"): "startDistanceJitter",
    ("RAYCAST", "distanceMod1"): "speed",
    ("RAYCAST", "distanceMod1Jitter"): "speedJitter",

    # BILLBOARD
    ("BILLBOARD3D", "EPVColorSlot1"): "correctColorNo",
    ("BILLBOARD3D", "SlotOverride1"): "colorRangeCorrectColorNo",
    ("BILLBOARD2D", "EPVColorSlot1"): "correctColorNo",
    ("BILLBOARD2D", "EPVColorSlot2"): "colorRangeCorrectColorNo",
    ("PLANE", "EPVColorSlot1"): "correctColorNo",
    ("PLANE", "EPVColorSlot2"): "colorRangeCorrectColorNo",
    ("BILLBOARD3D", "unknEnum5"): "divideNum",
    ("BILLBOARD3D", "unknFlag6_0"): "enableGPUParticle",
    ("BILLBOARD3D", "unkn6_1"): "fieldInfluenceRate",
    ("BILLBOARD3D", "unkn7"): "fieldInfluenceRateMultiplier",
    ("BILLBOARD3D", "unkn8"): "lightGroup",
    ("RIBBON", "unknBitmask22_1"): "lightGroup",
    ("PLANE", "unknBitmask7_0"): "lightGroup",

    # SPAWN
    ("SPAWN", "particlesPerBurst"): "spawnNum",
    ("SPAWN", "particlesPerBurstJitter"): "spawnNumJitter",
    ("SPAWN", "burstInterval"): "intervalFrame",
    ("SPAWN", "burstIntervalJitter"): "intervalFrameJitter",
    ("SPAWN", "burstsPerCycle"): "loopNum",
    ("SPAWN", "burstsPerCycleJitter"): "loopNumJitter",
    ("SPAWN", "emitterStartDelay"): "emitterDelayFrame",
    ("SPAWN", "emitterStartDelayJitter"): "emitterDelayFrameJitter",
    ("SPAWN", "particleSpawnDelay"): "particleDelayFrame",
    ("SPAWN", "particleSpawnDelayJitter"): "particleDelayFrameJitter",
    ("SPAWN", "unknBitmask31"): "spawnFlags",
    ("SPAWN", "instanceCountUnknLimit"): "spawnFrame",
    ("SPAWN", "instanceCountUnknLimitJitter"): "spawnFrameJitter",
    ("SPAWN", "emitterRepeatCount"): "revivalLoop",
    ("SPAWN", "altBurstInterval"): "revivalInterval",
    ("SPAWN", "altBurstIntervalJitter"): "revivalIntervalJitter",
    ("SPAWN", "ringBufferInterval"): "revivalInterval",
    ("SPAWN", "ringBufferIntervalJitter"): "revivalIntervalJitter",
    ("SPAWN", "spawnWaitFrame"): "particleDelayFrame",
    ("SPAWN", "spawnWaitFrameJitter"): "particleDelayFrameJitter",

    # ── EMITTERSHAPE2D ───────────────────────────────────────────────────────
    ("EMITTERSHAPE2D", "spawnCount"): "rangeDivideHorizontalNum",

    # ── SCALEANIM ────────────────────────────────────────────────────────────
    ("SCALEANIM", "unknFloat"): "sizeScalarAddJitter",
    ("SCALEANIM", "initialScaleSpeed"): "sizeScalarAdd",
    ("SCALEANIM", "initialScaleSpeedJitter"): "sizeScalarAddJitter",
    ("SCALEANIM", "initialScaleAccel"): "sizeScalarAddCoef",
    ("SCALEANIM", "initialScaleAccelJitter"): "sizeScalarAddCoefJitter",
    ("SCALEANIM", "scaleSpeedX"): "sizeXAdd",
    ("SCALEANIM", "scaleSpeedXJitter"): "sizeXAddJitter",
    ("SCALEANIM", "scaleAccelX"): "sizeXAddCoef",
    ("SCALEANIM", "scaleAccelXJitter"): "sizeXAddCoefJitter",
    ("SCALEANIM", "scaleSpeedY"): "sizeYAdd",
    ("SCALEANIM", "scaleSpeedYJitter"): "sizeYAddJitter",
    ("SCALEANIM", "scaleAccelY"): "sizeYAddCoef",
    ("SCALEANIM", "scaleAccelYJitter"): "sizeYAddCoefJitter",
    ("SCALEANIM", "scaleSpeedZ"): "sizeZAdd",
    ("SCALEANIM", "scaleSpeedZJitter"): "sizeZAddJitter",
    ("SCALEANIM", "scaleAccelZ"): "sizeZAddCoef",
    ("SCALEANIM", "scaleAccelZJitter"): "sizeZAddCoefJitter",

    # ── FADEBYANGLE ──────────────────────────────────────────────────────────
    ("FADEBYANGLE", "unknBitmask0_1"): "coneVisibilityFlags",
    ("FADEBYANGLE", "unkn_angle0"): "cutoffConeAngle",
    ("FADEBYANGLE", "unkn_angle1"): "fadeConeAngle",
    ("FADEBYANGLE", "unkn1_2"): "minAlpha",
    ("FADEBYANGLE", "unknBitmask2_0"): "baseAxis",
    ("FADEBYANGLE", "unknEnum2_1"): "rotOrder",

    # ── FADEBYOCCLUSION ──────────────────────────────────────────────────────
    ("FADEBYOCCLUSION", "unknFixed0_1"): "section_length",
    ("FADEBYOCCLUSION", "unkn1"): "spacer0",
    ("FADEBYOCCLUSION", "unkn2_0"): "occlusionRadius",
    ("FADEBYOCCLUSION", "unknFlag2_1"): "minScale",
    ("FADEBYOCCLUSION", "unknFlag2_2"): "minAlpha",

    # ── LIFE ─────────────────────────────────────────────────────────────────
    ("LIFE", "unkn2_0"): "unknFrame",
    ("LIFE", "unknEnum2_1"): "unknFrameJitter",

    # PTCOLLISION
    ("PTCOLLISION", "unkn06"): "projectionOffset",
    ("PTCOLLISION", "unkn07"): "projectionDist",
    ("PTCOLLISION", "unknEnum2_0"): "bounceCount",
    ("PTCOLLISION", "bounceCountLimit"): "bounceCount",
    ("PTCOLLISION", "unknEnum2_1"): "bounceCountJitter",
    ("PTCOLLISION", "unknEnum38"): "impactPlayTriggerMode",
    ("PTCOLLISION", "unknBitmask4_0"): "impactPlayTriggerCount",
    ("PTCOLLISION", "unknFlag4_1"): "impactPlayTriggerCountJitter",

    # UVCONTROL
    ("UVCONTROL", "uv1_unkn0"): "typeFlag",
    ("UVCONTROL", "uv1_unknFlag"): "typeFlag",
    ("UVCONTROL", "unknFlag2"): "enableFlowmap",
    ("UVCONTROL", "extraMaterialInitialPosition"): "flowSpeed",
    ("UVCONTROL", "extraMaterialInitialPositionJitter"): "flowSpeedJitter",
    ("UVCONTROL", "extraMaterialSpeed"): "flowSpeedCoef",
    ("UVCONTROL", "extraMaterialSpeedJitter"): "flowSpeedCoefJitter",
    ("UVCONTROL", "opacity"): "flowStrength",
    ("UVCONTROL", "opacityJitter"): "flowStrengthJitter",
    ("UVCONTROL", "opacityAcceleration"): "flowStrengthCoef",
    ("UVCONTROL", "opacityAccelerationJitter"): "flowStrengthCoefJitter",

    # ── BILLBOARD3D / BILLBOARD2D / PLANE ───────────────────────────────────
    ("BILLBOARD3D", "randomBrightnessMult"): "brightnessJitter",
    ("BILLBOARD2D", "randomBrightnessMult"): "brightnessJitter",
    ("PLANE", "randomBrightnessMult"): "brightnessJitter",

    # RIBBON
    ("RIBBON", "color2"): "colorRange",
    ("RIBBON", "unkn4_0"): "brightnessJitter",
    ("RIBBON", "unknEnum4_1"): "ribbonMode",
    ("RIBBON", "horizontal_physics_subdivision_count"): "subdivisionCount",
    ("RIBBON", "vertical_physics_subdivision_count"): "useTrailTimeScale",
    ("RIBBON", "restitution_direction"): "baseAxis",
    ("RIBBON", "unknEnum16arr_0"): "rotationOrder",
    ("RIBBON", "unkn16arr_1"): "rotationX",
    ("RIBBON", "unkn16arr_2"): "rotationXJitter",
    ("RIBBON", "unkn16arr_3"): "rotationYJitter",
    ("RIBBON", "startingAngle"): "rotationY",
    ("RIBBON", "startingAngleJitter"): "rotationZJitter",
    ("RIBBON", "unkn16_0_0"): "rotationZ",
    ("RIBBON", "unknown19_0"): "spawnAnchorOffset",
    ("RIBBON", "restitution"): "restoreStrength",
    ("RIBBON", "restitution_jitter"): "restoreStrengthJitter",
    ("RIBBON", "inertial_excess"): "inertia",
    ("RIBBON", "inertial_excess_jitter"): "inertiaJitter",
    ("RIBBON", "unknEnum22_1"): "lightGroup",
    ("RIBBON", "tailTiedToBone"): "enableFlowmap",
    ("RIBBON", "unkn23_0"): "flowSpeed",
    ("RIBBON", "unkn23_1"): "flowSpeedJitter",
    ("RIBBON", "unkn23_2"): "flowSpeedCoef",
    ("RIBBON", "unknFixed23_3"): "flowSpeedCoefJitter",
    ("RIBBON", "unkn23_4"): "flowStrength",
    ("RIBBON", "unkn23_5"): "flowStrengthJitter",
    ("RIBBON", "unkn23_6"): "flowStrengthCoef",
    ("RIBBON", "unknFixed23_7"): "flowStrengthCoefJitter",
    ("RIBBON", "base_flap_frequency"): "flap1Frequency",
    ("RIBBON", "base_flap_frequency_jitter"): "flap1FrequencyJitter",
    ("RIBBON", "base_flap_amount"): "flap1Amount",
    ("RIBBON", "base_flap_amount_jitter"): "flap1AmountJitter",
    ("RIBBON", "tip_flap_frequency"): "flap2Frequency",
    ("RIBBON", "tip_flap_frequency_jitter"): "flap2FrequencyJitter",
    ("RIBBON", "tip_flap_amount"): "flap2Amount",
    ("RIBBON", "tip_flap_amount_jitter"): "flap2AmountJitter",
    ("RIBBON", "unknBool8"): "enableFadeLength",
    ("RIBBON", "unkn27_0"): "base_fade_length",
    ("RIBBON", "unkn27_1"): "tip_fade_length",
    ("RIBBON", "ribbon_flow_unkn0"): "unknFixed28_0",
    ("RIBBON", "ribbon_flow_enable_a"): "enableGravity",
    ("RIBBON", "ribbon_flow_enable_b"): "gravityLocalSpace",
    ("RIBBON", "ribbon_flow_reserved"): "spacer28",
    ("RIBBON", "ribbon_flow_param0"): "gravityX",
    ("RIBBON", "ribbon_flow_param1"): "gravityY",
    ("RIBBON", "ribbon_flow_param2"): "gravityZ",
    ("RIBBON", "ribbon_flow_param3"): "unknFixed28_param3",
    ("RIBBON", "unknGlobalForceEnable"): "enableGravity",
    ("RIBBON", "unknBool28_2"): "gravityLocalSpace",
    ("RIBBON", "unknGlobalForceX"): "gravityX",
    ("RIBBON", "unknGlobalForceY"): "gravityY",
    ("RIBBON", "unknGlobalForceZ"): "gravityZ",
    ("RIBBON", "uv_map_height"): "uvScaleMode",
    ("RIBBON", "material_tesselation_density"): "uvScaleLength",
    ("RIBBON", "material_tesselation_jitter"): "uvScaleLengthJitter",
    ("RIBBON", "uv_map_width"): "uvScaleWidth",
    ("RIBBON", "unknBool15"): "useTrailTimeScale",
    ("RIBBON", "unkn15"): "trailTimeScale",

    # STRAINRIBBON
    ("STRAINRIBBON", "color3_z"): "enableFlowmap",
    ("STRAINRIBBON", "unkn06_0"): "flowSpeed",
    ("STRAINRIBBON", "unkn06_1"): "flowSpeedJitter",
    ("STRAINRIBBON", "unkn06_2"): "flowSpeedCoef",
    ("STRAINRIBBON", "unknFixed06_3"): "flowSpeedCoefJitter",
    ("STRAINRIBBON", "unkn06_4"): "flowStrength",
    ("STRAINRIBBON", "unknFlag06_5"): "flowStrengthJitter",
    ("STRAINRIBBON", "unkn06_6"): "flowStrengthCoef",
    ("STRAINRIBBON", "unkn06_7"): "flowStrengthCoefJitter",
    ("PTCOLLISION", "bounceCountLimitJitter"): "bounceCountJitter",
    ("PTCOLLISION", "impactPlayTriggerCountRandom"): "impactPlayTriggerCountJitter",
    ("PTCOLLISION", "bounceElasticityBonus"): "bounceElasticityMultiplier",

    ("ALPHACORRECTION", "transparentness"): "contrast_gamma",
    ("ALPHACORRECTION", "unkn1"): "lowPass",
    ("BILLBOARD2D", "unkn0_0"): "typeFlag",
    ("BILLBOARD3D", "unkn0"): "typeFlag",
    ("BLINK", "unkn0_0"): "typeFlag",
    ("BLINK", "unkn0_1"): "section_length",
    ("BLINK", "minAlpha"): "minAlphaRate",
    ("BLINK", "maxAlpha"): "maxAlphaRate",
    ("BLINK", "lowFreq"): "lowFrequency",
    ("BLINK", "lowFreqJitter"): "lowFrequencyJitter",
    ("BLINK", "lowFreqAmplitude"): "lowFrequencyWidth",
    ("BLINK", "lowFreqAmplitudeJitter"): "lowFrequencyWidthJitter",
    ("BLINK", "highFreq"): "highFrequency",
    ("BLINK", "highFreqJitter"): "highFrequencyJitter",
    ("BLINK", "highFreqAmplitude"): "highFrequencyWidth",
    ("BLINK", "highFreqAmplitudeJitter"): "highFrequencyWidthJitter",
    ("CHECKPUREATTRIBUTE", "unkn0_0"): "typeFlag",
    ("CHECKPUREATTRIBUTE", "unkn0_1"): "section_length",
    ("COLORCORRECTFILTER", "unkn0_0"): "typeFlag",
    ("DUMMY", "unkn0_0"): "typeFlag",
    ("DUMMY", "unkn0_1"): "section_length",
    ("EMITTERBOUNDARY", "unkn0_0"): "typeFlag",
    ("EMITTERBOUNDARY", "unknEnum0_1"): "boundaryType",
    ("EMITTERBOUNDARY", "unkn1_0"): "radius",
    ("EMITTERBOUNDARY", "unkn1_7"): "radius2",
    ("EMITTERSHAPE2D", "unkn0"): "typeFlag",
    ("EMITTERSHAPE3D", "unkn0"): "typeFlag",
    ("EMITTERSHAPE3D", "patternControl"): "shapeType",
    ("EMITTERSHAPE3D", "spawnPerCycle"): "rangeDivideHorizontalNum",
    ("EMITTERSHAPE3D", "spawnTotal"): "rangeDivideVerticalNum",
    ("EMITTERSHAPE3D", "transform"): "rangeXYZ",
    ("EMITTERSHAPE3D", "trayectoryRotationX"): "localRotationX",
    ("EMITTERSHAPE3D", "trayectoryRotationY"): "localRotationY",
    ("EMITTERSHAPE3D", "trayectoryRotationZ"): "localRotationZ",
    ("EMITTERSHAPE3D", "unknEnum2"): "rangeDivideAxis",
    ("EMITTERSHAPE3D", "unknEnum3_0"): "rotationCorrect",
    ("EMITTERSHAPEMESH", "unkn0_0"): "typeFlag",
    ("EMITTERSHAPEMESH", "unkn2_1"): "ddsUsageType",
    ("EMITTERSHAPEMESH", "unkn2_3"): "visconIndex",
    ("EXTERNREFERENCE", "unkn0"): "typeFlag",
    ("FADEBYANGLE", "unkn0_0"): "typeFlag",
    ("FADEBYDEPTH", "unkn0"): "typeFlag",
    ("FADEBYEMITTERANGLE", "unkn0_0"): "typeFlag",
    ("FADEBYEMITTERANGLE", "unkn0_1"): "section_length",
    ("FADEBYOCCLUSION", "unkn0_0"): "typeFlag",
    ("FAKEDOF", "unkn0"): "typeFlag",
    ("FAKEDOF", "unkn1"): "section_length",
    ("FAKEPLANE", "unkn0_0"): "typeFlag",
    ("FAKEPLANE", "unkn0_1"): "section_length",
    ("HOMING", "unknown"): "typeFlag",
    ("HOMING", "unknown0"): "section_length",
    ("HOMING", "enableRadialVanish"): "forceFieldMode",
    ("HOMING", "i0"): "homingTarget",
    ("HOMING", "i1"): "vanishMode",
    ("LIFE", "unkn0"): "typeFlag",
    ("LIGHTNING", "unkn00_0"): "typeFlag",
    ("LINKPARTSVISIBLE", "unkn0_0"): "typeFlag",
    ("MASTERONLY", "unkn0"): "typeFlag",
    ("NOISE", "secondary_axis_speed"): "lowFrequencyJitter",
    ("NOISE", "secondary_axis_speed2"): "highFrequencyJitter",
    ("NOISE", "smooth_radius_randomized"): "lowFrequencyWidthJitter",
    ("NOISE", "smooth_radius_randomized2"): "highFrequencyWidthJitter",
    ("NOISE", "main_axis_speed"): "lowFrequency",
    ("NOISE", "main_axis_speed_jitter"): "lowFrequencyJitter",
    ("NOISE", "teleport_radius"): "lowFrequencyWidth",
    ("NOISE", "teleport_radius_jitter"): "lowFrequencyWidthJitter",
    ("NOISE", "main_axis_speed2"): "highFrequency",
    ("NOISE", "main_axis_speed2_jitter"): "highFrequencyJitter",
    ("NOISE", "teleport_radius2"): "highFrequencyWidth",
    ("NOISE", "teleport_radius2_jitter"): "highFrequencyWidthJitter",
    ("OTOMOSNOW", "unkn0_0"): "typeFlag",
    ("OTOMOSNOW", "unkn0_1"): "section_length",
    ("PARENTEMISSIVE", "unkn0"): "typeFlag",
    ("PARENTEMISSIVE", "unkn2"): "blend",
    ("PARENTEMISSIVE", "unknEnum3"): "correctColorNo",
    ("PARENTEMISSIVE", "color"): "emissive",
    ("PARENTEMISSIVE", "brightness"): "intensity",
    ("PARENTMATERIAL", "unkn0_0"): "typeFlag",
    ("PARENTOPTIONS", "unkn0"): "typeFlag",
    ("PARENTSNOW", "unkn0_0"): "typeFlag",
    ("PARENTSNOW", "unkn0_1"): "section_length",
    ("PATHCHAIN", "unkn0_0"): "typeFlag",
    ("PATHCHAIN", "unkn0_1"): "section_length",
    ("PATHCHAIN", "unknFixed4_1"): "unkn4_0Jitter",
    ("PATHCHAIN", "unknFixed4_3"): "unkn4_2Jitter",
    ("PATHCHAIN", "unknFixed4_5"): "unkn4_4Jitter",
    ("PATHCHAIN", "unknBitmask5_0"): "baseAxis",
    ("PATHCHAIN", "unkn5_1"): "rotationX",
    ("PATHCHAIN", "unkn5_2"): "rotationXJitter",
    ("PATHCHAIN", "unkn5_3"): "rotationY",
    ("PATHCHAIN", "unknFixed5_4"): "rotationYJitter",
    ("PATHCHAIN", "unkn5_5"): "rotationZ",
    ("PATHCHAIN", "unknFixed5_6"): "rotationZJitter",
    ("PLEMISSIVE", "unkn0_0"): "typeFlag",
    ("PLEMISSIVE", "unknEnum0_1"): "priority",
    ("PLEMISSIVE", "unkn1"): "blend",
    ("PLEMISSIVE", "epv_color_slot"): "correctColorNo",
    ("PLEMISSIVE", "color"): "emissive",
    ("PLEMISSIVE", "unkn4"): "intensity",
    ("PLEMISSIVE", "bright"): "rimAlpha",
    ("PLEMISSIVE", "area_of_aura"): "emitMaskFlags",
    ("PLEMISSIVE", "radii_effect_unkn0"): "mask0",
    ("PLEMISSIVE", "radii_effect_unkn1"): "mask1",
    ("PLEMISSIVE", "radii_effect_unkn2"): "enableUseEmitMask",
    ("PLEMISSIVE", "unkn5_1"): "addMask0",
    ("PLEMISSIVE", "unkn5_2"): "addMask1",
    ("PLSNOW", "unkn0_0"): "typeFlag",
    ("PTCOLLISION", "unkn00"): "typeFlag",
    ("PTLIFE", "unkn0"): "typeFlag",
    ("PTTRIGGER", "unkn0_0"): "typeFlag",
    ("PTTRIGGER", "unkn0_1"): "section_length",
    ("RAYCAST", "fixed70"): "section_length",
    ("RAYCAST", "unknown0"): "typeFlag",
    ("REFRACTION", "unkn0"): "typeFlag",
    ("REFRACTION", "unkn2"): "alphaBlend",
    ("REFRACTION", "seeThroughBlend"): "alphaBlend",
    ("REFRACTION", "pixelNormalOffset"): "distortionType",
    ("RGBFIRE", "unkn0"): "typeFlag",
    ("RGBFIRE", "color1"): "fireColor",
    ("RGBFIRE", "color2"): "smokeColor",
    ("RGBFIRE", "brightness1"): "fireFactor",
    ("RGBFIRE", "unkn4"): "lerpAlphaToBlue",
    ("RGBFIRE", "brightness2"): "redChFactor",
    ("RGBFIRE", "brightness3"): "alphaFactor",
    ("RGBFIRE", "brightness4"): "colorRate",
    ("RGBFIRE", "alphaRate"): "alphaFactor",
    ("RGBFIRE", "fireColorParam_unkn9"): "fireColorParam_correctColorNo",
    ("RGBFIRE", "smokeColorParam_unkn9"): "smokeColorParam_correctColorNo",
    ("RGBWATER", "unkn0"): "typeFlag",
    ("RIBBON", "unkn0"): "typeFlag",
    ("RIBBONBLADE", "unkn0_0"): "typeFlag",
    ("RIBBONBLADE", "NULL5"): "flowSpeedJitter",
    ("RIBBONBLADE", "NULL6"): "flowSpeedCoefJitter",
    ("RIBBONBLADE", "NULL7"): "flowStrengthJitter",
    ("RIBBONBLADE", "NULL8"): "flowStrengthCoefJitter",
    ("RIBBONBLADE", "unkn03"): "widthDirection",
    ("RIBBONBLADE", "unkn04"): "width",
    ("RIBBONBLADE", "unkn05_0"): "length",
    ("RIBBONBLADE", "unkn07_1"): "lengthMode",
    ("RIBBONBLADE", "unkn23"): "flowSpeed",
    ("RIBBONBLADE", "unkn24"): "flowSpeedCoef",
    ("RIBBONBLADE", "unkn25"): "flowStrength",
    ("RIBBONBLADE", "unkn26"): "flowStrengthCoef",
    ("ROTATEANIM", "billboardRotationSpeed"): "billboardRotationJitter",
    ("ROTATEANIM", "momentum_retention"): "spinSpeedCoefX",
    ("ROTATEANIM", "unkn0_0"): "spinAxisMask",
    ("ROTATEANIM", "unkn1_0"): "billboardRotationCoef",
    ("ROTATEANIM", "unkn1_1"): "billboardRotationCoefJitter",
    ("ROTATEANIM", "unknEnum1_2"): "rotateDelayStartJitter",
    ("SCALEANIM", "unkn0"): "typeFlag",
    ("SCALEANIM", "delayJitter"): "animUpdateStartJitter",
    ("SCALEANIM", "scaleAccelJitter"): "sizeXAddCoefJitter",
    ("SCALEANIM", "scaleSpeedJitter"): "sizeScalarAddCoefJitter",
    ("SCREENSPACECOLLISION", "unkn0_0"): "typeFlag",
    ("SCREENSPACECOLLISION", "unkn0_1"): "section_length",
    ("SHADERSETTINGS", "unkn0"): "typeFlag",
    ("SHADERSETTINGS", "unknEnum4_8"): "presetId",
    ("SHADERSETTINGS", "zDepthModifierStart"): "depthBias",
    ("SHADERSETTINGS", "zDepthModifierEnd"): "softParticleDistance",
    ("SHOVEL", "unkn00"): "typeFlag",
    ("SHOVEL", "unkn01"): "section_length",
    ("SPAWN", "unkn0"): "typeFlag",
    ("SPAWN", "durationOfSpawnerLifespan"): "loopNum",
    ("SPAWN", "frameDelayBetweenSpawns"): "intervalFrame",
    ("SPAWN", "instancesSpawnedPerFrame"): "spawnNum",
    ("SPAWN", "instancesSpawnedTotal"): "maxParticles",
    ("SPAWN", "occur"): "emitterDelayFrame",
    ("SPAWN", "occur2"): "emitterDelayFrameJitter",
    ("SPAWN", "randomizedDelay"): "intervalFrameJitter",
    ("SPAWN", "randomizedLifespan"): "loopNumJitter",
    ("SPAWN", "randomizedSpawnsPerFrame"): "spawnNumJitter",
    ("SPAWN", "repeatAtribute"): "revivalLoop",
    ("SPAWN", "unkn10"): "particleDelayFrame",
    ("SPAWN", "unkn21"): "revivalInterval",
    ("SPAWN", "unkn30"): "revivalIntervalJitter",
    ("SPAWN", "unknEnum11"): "particleDelayFrameJitter",
    ("SPAWNBYANGLE", "unkn0_0"): "typeFlag",
    ("SPAWNBYANGLE", "unkn0_1"): "section_length",
    ("SPAWNBYOCCLUSION", "unkn0_0"): "typeFlag",
    ("SPAWNBYOCCLUSION", "unkn0_1"): "section_length",
    ("STRAINRIBBON", "unkn00_0"): "typeFlag",
    ("STRAINRIBBON", "unkn01_0"): "useColorRange",
    ("STRAINRIBBON", "unkn02_0"): "useEmission",
    ("STRAINRIBBON", "unkn10_01"): "angleRelated",
    ("STRAINRIBBON", "unkn10_02"): "angleRelatedJitter",
    ("TONEMAPFILTER", "unkn0_0"): "typeFlag",
    ("TONEMAPFILTER", "unknFixed2_0"): "intensity",
    ("TONEMAPFILTER", "unknFixed2_1"): "triggerRadius",
    ("TRANSFORM2D", "unknown"): "typeFlag",
    ("TRANSFORM3D", "unkn0"): "typeFlag",
    ("UVCONTROL", "uv2_unkn0"): "uv2_enable",
    ("UVSEQUENCE", "unkn0"): "typeFlag",
    ("VELOCITY2D", "unkn0_0"): "typeFlag",
    ("VELOCITY2D", "expansionRadiusElasticity"): "speedCoef",
    ("VELOCITY2D", "expansionRadiusElasticityJitter"): "speedCoefJitter",
    ("VELOCITY2D", "expansionType"): "velocityType",
    ("VELOCITY2D", "initialVelocity"): "speed",
    ("VELOCITY2D", "initialVelocityDelay"): "movementDelay",
    ("VELOCITY2D", "initialVelocityDelayJitter"): "movementDelayJitter",
    ("VELOCITY2D", "initialVelocityJitter"): "speedJitter",
    ("VELOCITY2D", "offsetX"): "velocityX",
    ("VELOCITY2D", "offsetY"): "velocityY",
    ("VELOCITY2D", "sizeX"): "divergenceX",
    ("VELOCITY2D", "sizeY"): "divergenceY",
    ("VELOCITY2D", "unkn0_1"): "rotation",
    ("VELOCITY2D", "unkn10"): "rotationJitter",

    # 多类型共用的 flowmap 系数字段。
    **{
        (_t, _old): _new
        for _t in ("BILLBOARD2D", "BILLBOARD3D", "LIGHTNING", "PLANE",
                   "RIBBON", "RIBBONBLADE", "STRAINRIBBON", "UVCONTROL")
        for _old, _new in (
            ("flowmapAcceleration",               "flowSpeedCoef"),
            ("flowmapAccelerationJitter",         "flowSpeedCoefJitter"),
            ("flowmapStrengthAcceleration",       "flowStrengthCoef"),
            ("flowmapStrengthAccelerationJitter", "flowStrengthCoefJitter"),
        )
    },

    # 流动贴图组按 DTI FlowmapSettings 官方名改名。
    **{
        (_t, _old): _new
        for _t in ("BILLBOARD2D", "BILLBOARD3D", "LIGHTNING", "PLANE",
                   "RIBBON", "RIBBONBLADE", "STRAINRIBBON", "UVCONTROL")
        for _old, _new in (
            ("flowmapSpeed",              "flowSpeed"),
            ("flowmapSpeedJitter",        "flowSpeedJitter"),
            ("flowmapSpeedCoef",          "flowSpeedCoef"),
            ("flowmapSpeedCoefJitter",    "flowSpeedCoefJitter"),
            ("flowmapStrength",           "flowStrength"),
            ("flowmapStrengthJitter",     "flowStrengthJitter"),
            ("flowmapStrengthCoef",       "flowStrengthCoef"),
            ("flowmapStrengthCoefJitter", "flowStrengthCoefJitter"),
        )
    },
    ("RIBBON", "flowmapPlayOnce"): "flowOnce",
    ("RIBBON", "unknBool16_2_1"): "faceVelocity",
    ("RIBBON", "unknBool3a"): "fixedDirection",
    ("RIBBON", "unknBool3b"): "lockInitialVelocity",
    ("RIBBON", "unknBool5"): "stretchFromSpawn",
    ("RIBBON", "unkn20_0"): "stretchMaxLength",
    ("RIBBON", "unkn20_1"): "stretchMaxLengthJitter",
    ("RIBBON", "unkn20_2"): "stretchResetDistance",
    ("RIBBON", "unkn20_3"): "stretchResetDistanceJitter",
    ("RIBBON", "flowmapReverse"): "flowReverse",

    # UVCONTROL
    ("UVCONTROL", "uv1_initialPosition"): "uv1_offset",
    ("UVCONTROL", "uv1_speed"): "uv1_offsetAdd",
    ("UVCONTROL", "uv1_acceleration"): "uv1_offsetCoef",
    ("UVCONTROL", "uv1_scaleSpeed"): "uv1_scaleAdd",
    ("UVCONTROL", "uv1_scaleAcceleration"): "uv1_scaleCoef",
    ("UVCONTROL", "uv2_initialPosition"): "uv2_offset",
    ("UVCONTROL", "uv2_speed"): "uv2_offsetAdd",
    ("UVCONTROL", "uv2_acceleration"): "uv2_offsetCoef",
    ("UVCONTROL", "uv2_scaleSpeed"): "uv2_scaleAdd",
    ("UVCONTROL", "uv2_scaleAcceleration"): "uv2_scaleCoef",

    # UVSEQUENCE
    ("UVSEQUENCE", "uvs_index"): "sequenceNo",
    ("UVSEQUENCE", "uvsIndex"): "sequenceNo",
    ("UVSEQUENCE", "uvsIndexJitter"): "sequenceNoJitter",
    ("UVSEQUENCE", "unkn2"): "sequenceNoJitter",
    ("UVSEQUENCE", "startingFrame"): "patternNo",
    ("UVSEQUENCE", "startingFrameJitter"): "patternNoJitter",
    # MESH
    ("MESH", "unknFloat0"): "playSpeed",
    ("MESH", "unknFloat1"): "playSpeedJitter",
    ("MESH", "emissive_saturation"): "colorRate",
    ("MESH", "emissive_saturation_j"): "colorRateJitter",
    ("MESH", "emissive_brightness"): "emissiveColorRate",
    ("MESH", "emissive_brightness_j"): "emissiveColorRateJitter",
    ("UVSEQUENCE", "animationSpeed"): "playSpeed",
    ("UVSEQUENCE", "animationSpeedJitter"): "playSpeedJitter",
    ("UVSEQUENCE", "animationAcceleration"): "playSpeedCoef",
    ("UVSEQUENCE", "animationAccelerationJitter"): "playSpeedCoefJitter",

    # ROTATEANIM
    ("ROTATEANIM", "billboardRotationAccel"): "billboardRotationCoef",
    ("ROTATEANIM", "billboardRotationAccelJitter"): "billboardRotationCoefJitter",
    ("ROTATEANIM", "spinAccelerationX"): "spinSpeedCoefX",
    ("ROTATEANIM", "spinAccelerationXJitter"): "spinSpeedCoefXJitter",
    ("ROTATEANIM", "spinAccelerationY"): "spinSpeedCoefY",
    ("ROTATEANIM", "spinAccelerationYJitter"): "spinSpeedCoefYJitter",
    ("ROTATEANIM", "spinAccelerationZ"): "spinSpeedCoefZ",
    ("ROTATEANIM", "spinAccelerationZJitter"): "spinSpeedCoefZJitter",

    # VELOCITY
    ("VELOCITY3D", "acceleration"): "speedCoef",
    ("VELOCITY3D", "accelerationJitter"): "speedCoefJitter",
    ("VELOCITY3D", "elasticity"): "speedCoef",
    ("VELOCITY3D", "elasticityJitter"): "speedCoefJitter",
    ("VELOCITY3D", "velocityX"): "offsetX",
    ("VELOCITY3D", "velocityY"): "offsetY",
    ("VELOCITY3D", "velocityZ"): "offsetZ",
    ("VELOCITY3D", "divergenceX"): "sizeX",
    ("VELOCITY3D", "divergenceY"): "sizeY",
    ("VELOCITY3D", "divergenceZ"): "sizeZ",
    ("VELOCITY2D", "acceleration"): "speedCoef",
    ("VELOCITY2D", "accelerationJitter"): "speedCoefJitter",

    # PARENTOPTIONS
    ("PARENTOPTIONS", "translation_tracking"): "relationPos",
    ("PARENTOPTIONS", "angle_tracking"): "relationRot",
    ("PARENTOPTIONS", "scale_tracking"): "relationScl",
    ("PARENTOPTIONS", "spawnTrack"): "particleUseLocal",
    ("PARENTOPTIONS", "lockToPositionFrame"): "constRelease",
    ("PARENTOPTIONS", "lockToPositionFrameJitter"): "constReleaseJitter",
    ("PARENTOPTIONS", "spawnLock"): "constRelease",
    ("PARENTOPTIONS", "unknFlag1"): "invalidParticleScale",
    ("PARENTOPTIONS", "bleedPos"): "constReleaseJitter",
    ("PARENTOPTIONS", "bone_lim"): "jointNo",

    # RGBFIRE 生命周期字段。
    **{
        (_t, f"{_p}ColorParam_{_old}"): f"{_p}ColorParam_{_new}"
        for _t in ("RGBFIRE",)
        for _p in ("fire", "smoke")
        for _old, _new in (
            ("enable",         "useLife"),
            ("fadeIn",         "appearFrame"),
            ("fadeInJitter",   "appearFrameJitter"),
            ("duration",       "keepFrame"),
            ("durationJitter", "keepFrameJitter"),
            ("fadeOut",        "vanishFrame"),
            ("fadeOutJitter",  "vanishFrameJitter"),
            ("unkn7",          "lighting"),
            ("unkn8",          "lifeType"),
        )
    },

    # LIGHTNING 的字段拆分不能由本表兼容。

    # PLANE
    ("PLANE", "unknBitmask5_2"): "baseAxis",
    ("PLANE", "unknEnum5_3"): "rotationOrder",

    # MESH
    ("MESH", "starting_model_viscon"): "visconIndex",
    ("MESH", "unknBitmask40"): "baseAxis",
    ("EXTERNMESH", "unknBitmask40"): "baseAxis",
    ("MESH", "end_model_viscon"): "visconIndexJitter",

    # PTLIFE
    ("PTLIFE", "unknEnum6"): "unknFrame0",
    ("PTLIFE", "unknFixed7"): "unknFrame0Jitter",
    ("PTLIFE", "unknEnum8"): "unknFrame1",
    ("PTLIFE", "unknFixed9"): "unknFrame1Jitter",

    # RGBWATER
    ("RGBWATER", "unknownFlagInt_0"): "colorParam0_useLife",
    ("RGBWATER", "unknownEnumInt_1"): "colorParam0_appearFrame",
    ("RGBWATER", "unknownEnumInt_2"): "colorParam0_appearFrameJitter",
    ("RGBWATER", "unknEnum2_0"): "colorParam0_keepFrame",
    ("RGBWATER", "unknEnum2_1"): "colorParam0_keepFrameJitter",
    ("RGBWATER", "unknEnum2_2"): "colorParam0_vanishFrame",
    ("RGBWATER", "unknEnum2_3"): "colorParam0_vanishFrameJitter",
    ("RGBWATER", "unknFlag2_4"): "colorParam0_lighting",
    ("RGBWATER", "unknFlag2_5"): "colorParam0_lifeType",
    ("RGBWATER", "unknEnum2_6"): "colorParam0_unkn9",
    ("RGBWATER", "unknFlag2_7"): "colorParam1_useLife",
    ("RGBWATER", "unknEnum2_8"): "colorParam1_appearFrame",
    ("RGBWATER", "unknEnum2_9"): "colorParam1_appearFrameJitter",
    ("RGBWATER", "unkn2_10"): "colorParam1_keepFrame",
    ("RGBWATER", "unknEnum2_11"): "colorParam1_keepFrameJitter",
    ("RGBWATER", "unkn2_12"): "colorParam1_vanishFrame",
    ("RGBWATER", "unknEnum2_13"): "colorParam1_vanishFrameJitter",
    ("RGBWATER", "unknFlag2_14"): "colorParam1_lighting",
    ("RGBWATER", "unknEnum2_15"): "colorParam1_lifeType",
    ("RGBWATER", "unknEnum2_16"): "colorParam1_unkn9",
    ("RGBWATER", "unknFlag2_17"): "colorParam2_useLife",
    ("RGBWATER", "unknEnum2_18"): "colorParam2_appearFrame",
    ("RGBWATER", "unknEnum2_19"): "colorParam2_appearFrameJitter",
    ("RGBWATER", "unkn2_20"): "colorParam2_keepFrame",
    ("RGBWATER", "unknEnum2_21"): "colorParam2_keepFrameJitter",
    ("RGBWATER", "unkn2_22"): "colorParam2_vanishFrame",
    ("RGBWATER", "unknEnum2_23"): "colorParam2_vanishFrameJitter",
    ("RGBWATER", "unknFlag2_24"): "colorParam2_lighting",
    ("RGBWATER", "unknEnum2_25"): "colorParam2_lifeType",

    # RGBWATER 头部
    ("RGBWATER", "brightnessSlot1"): "colorRate",
    ("RGBWATER", "emissiveMultiplier"): "waterLerpGtoB",
    ("RGBWATER", "brightnessSlotMultiplier2"): "intensitySheet",
    # 数组旧名的两个子项与当前字段一一对应，可作为纯改名兼容。
    ("RGBWATER", "color[0]"): "colorSpecular",
    ("RGBWATER", "color[1]"): "colorSheet",
    ("RGBWATER", "color_0"): "colorSpecular",
    ("RGBWATER", "color_1"): "colorSheet",
    ("RGBWATER", "brightnessSlot2"): "intensityCubeMap",
    ("RGBWATER", "brightnessSlotMultiplier1"): "intensitySpecular",
    ("RGBWATER", "opacity"): "intensityAlpha",
    ("RGBWATER", "unknownFloat"): "normalSharpness",

    # RGBWATER 生命周期字段。
    ("RGBWATER", "colorParam0_useLife"): "specularColorParam_useLife",
    ("RGBWATER", "colorParam0_appearFrame"): "specularColorParam_appearFrame",
    ("RGBWATER", "colorParam0_appearFrameJitter"): "specularColorParam_appearFrameJitter",
    ("RGBWATER", "colorParam0_keepFrame"): "specularColorParam_keepFrame",
    ("RGBWATER", "colorParam0_keepFrameJitter"): "specularColorParam_keepFrameJitter",
    ("RGBWATER", "colorParam0_vanishFrame"): "specularColorParam_vanishFrame",
    ("RGBWATER", "colorParam0_vanishFrameJitter"): "specularColorParam_vanishFrameJitter",
    ("RGBWATER", "colorParam0_lighting"): "specularColorParam_lighting",
    ("RGBWATER", "colorParam0_lifeType"): "specularColorParam_lifeType",
    ("RGBWATER", "colorParam0_unkn9"): "specularColorParam_correctColorNo",
    ("RGBWATER", "specularColorParam_unkn9"): "specularColorParam_correctColorNo",
    ("RGBWATER", "colorParam1_useLife"): "sheetColorParam_useLife",
    ("RGBWATER", "colorParam1_appearFrame"): "sheetColorParam_appearFrame",
    ("RGBWATER", "colorParam1_appearFrameJitter"): "sheetColorParam_appearFrameJitter",
    ("RGBWATER", "colorParam1_keepFrame"): "sheetColorParam_keepFrame",
    ("RGBWATER", "colorParam1_keepFrameJitter"): "sheetColorParam_keepFrameJitter",
    ("RGBWATER", "colorParam1_vanishFrame"): "sheetColorParam_vanishFrame",
    ("RGBWATER", "colorParam1_vanishFrameJitter"): "sheetColorParam_vanishFrameJitter",
    ("RGBWATER", "colorParam1_lighting"): "sheetColorParam_lighting",
    ("RGBWATER", "colorParam1_lifeType"): "sheetColorParam_lifeType",
    ("RGBWATER", "colorParam1_unkn9"): "sheetColorParam_correctColorNo",
    ("RGBWATER", "sheetColorParam_unkn9"): "sheetColorParam_correctColorNo",
    ("RGBWATER", "colorParam2_useLife"): "waterLerpParam_useLife",
    ("RGBWATER", "colorParam2_appearFrame"): "waterLerpParam_appearFrame",
    ("RGBWATER", "colorParam2_appearFrameJitter"): "waterLerpParam_appearFrameJitter",
    ("RGBWATER", "colorParam2_keepFrame"): "waterLerpParam_keepFrame",
    ("RGBWATER", "colorParam2_keepFrameJitter"): "waterLerpParam_keepFrameJitter",
    ("RGBWATER", "colorParam2_vanishFrame"): "waterLerpParam_vanishFrame",
    ("RGBWATER", "colorParam2_vanishFrameJitter"): "waterLerpParam_vanishFrameJitter",
    ("RGBWATER", "colorParam2_lighting"): "waterLerpParam_lighting",
    ("RGBWATER", "colorParam2_lifeType"): "waterLerpParam_lifeType",

    # EMITTERSHAPE2D
    ("EMITTERSHAPE2D", "unknEnum22_0"): "rangeDivideAxis",

    # TUBELIGHT：旧名 lightIntensity 与当前字段重名，旧数据必须重新导入。
    ("TUBELIGHT", "lightIntensity"): "coreIntensity",
    ("TUBELIGHT", "lightIntensityJitter"): "coreIntensityJitter",
    ("TUBELIGHT", "coreThickness"): "coreIntensity",
    ("TUBELIGHT", "coreThicknessJitter"): "coreIntensityJitter",
    ("TUBELIGHT", "unkn2_1"): "textureScrollSpeed",
    ("TUBELIGHT", "unknFixed1_1"): "lightIntensity",
    ("TUBELIGHT", "unkn1_8"): "effectiveRadius",
    ("TUBELIGHT", "backFaceTintMode"): "tailEffectiveRadius",
    ("TUBELIGHT", "frontFaceTintMode"): "headEffectiveRadius",

    # STRAINRIBBON
    ("STRAINRIBBON", "colorModeFlag"): "epv_color_slot1",
    ("STRAINRIBBON", "positionalAberration_04"): "epv_color_slot2",
}


# 一个 int 字段按小端字节拆成四个单字节字段；字节不变，旧值可以无损换算。
FIELD_BYTE_SPLITS = {
    ("LAYOUT", "unknEnum1_0"): ("unknFixed1_0_0", "useColumn0", "useColumn1", "unknFlag1_0_3"),
    ("LAYOUT", "unknEnum1_1"): ("useColumn2", "useColumn4", "useColumn6", "useColumn7"),
}


def split_int_bytes(value) -> tuple:
    """按小端把一个 32 位整数拆成四个无符号字节。"""
    v = int(value) & 0xFFFFFFFF
    return tuple((v >> (8 * i)) & 0xFF for i in range(4))
